#!/bin/sh
#
# paleta - change terminal colors on the fly.

usage() {
    cat >&2 <<EOF
usage: ${0##*/} < PALETTE
       ... | ${0##*/}
       ${0##*/} -v
EOF
    exit 69
}

while getopts :v arg >/dev/null 2>&1; do
    case "${arg}" in
        v)
            printf 'paleta 1.0.0\n'
            exit
            ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))

set --

while read -r col; do
    [ "$#" -gt 259 ] && {
        printf 'warn: more than 259 colors given, ignoring excess\n' >&2
        break
    }

    [ "$col" = "${col#\#}" ] && col="#$col"
    set -- "$@" "${col##}"
done

[ "$#" -lt 19 ] && {
    printf 'warn: less than 19 colors given, duplicating input\n' >&2

    while [ "$#" -lt 19 ]; do
        set -- "$@" "${2:-FFFFFF}"
    done
}

# 10: Foreground color, 11: Background color, 12: Cursor Foreground color.
# Source:http://pod.tst.eu/http://cvs.schmorp.de/rxvt-unicode/doc/rxvt.7.pod#XTerm_Operating_System_Commands
seq="]10;$1\\]11;$2\\]12;$3\\"
shift 3

# Construct sequence list of 0-15 colors.
for col; do
    seq="$seq]4;${i:=0};${col}\\"

    [ "$((i += 1))" -gt 259 ] && break
done

# Border Background color (various terminals).
seq="$seq]708;$1\\"

# Send escape sequences to all open terminals.
for tty in /dev/pts/[0-9]*; do
    [ -w "$tty" ] && printf %b "$seq" > "$tty" &
done
printf %b "$seq"
